name: wfile
description: Convenient work with files and their content across multiple platforms.
repository: https://github.com/signmotion/wfile

topics:
  - files
  - xml
  - loader
  - filesystem
  - crossplatform

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.3.4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  image: ^4.1.7
  json_dart: ^0.1.0
  path: ">=1.8.0 <2.0.0"
  test: ^1.25.2
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
